### ISSUE TITLE
Plz upload point cloud code!

### ISSUE THREAD

**Issue by gardenlee21** [AutodeskAILab/Clip-Forge#11]
Hi, I want to reproduce your code based on the point cloud dataset. In your Readme, you will upload the point cloud code soon, but I cannot find it. Please upload the point cloud code. Thanks :)

**Comment by sanghiad** [comment]
@gardenlee21 I plan to add it soon. Hopefully by end of next week.

**Comment by gardenlee21** [comment]
Can you tell me when the point cloud code will be uploaded? Thanks for sharing! I believe your sharing will help the academic development.

**Comment by sanghiad** [comment]
Sorry for the delay @gardenlee21. Can you please wait till Sept 3rd? Do you have a deadline before then? I promise to upload it by then, I am currently busy for a deadline.

**Comment by sanghiad** [comment]
I had uploaded the pointcloud version on Sept 3rd. Let me know if anyone has problems with it :)

**Comment by AndreAmaduzzi** [comment]
Hi! The training code for point clouds seems to work well.
When are you going to release the test code to compute the metrics on the generated point clouds?

Thanks

**Comment by sanghiad** [comment]
@AndreAmaduzzi I did not make any new metrics for pointcloud. You can probably define similar metrics as define in paper by training your own pointcloud classifier.
