### ISSUE TITLE
Pre-training weights

### ISSUE THREAD

**Issue by happysxpp** [AutodeskAILab/Clip-Forge#18]
1. Could you share the pre-training weights provided for Stage 1 ?

2. Are there any plans to release point cloud code?

**Comment by dqj5182** [comment]
@happysxpp Did you fine pre-trained checkpoints for CLIP-Forge?

**Comment by happysxpp** [comment]
> @happysxpp Did you fine pre-trained checkpoints for CLIP-Forge?

@dqj5182 Sorry, I didn't
