### ISSUE TITLE
How to get 3d model from the output?

### ISSUE THREAD

**Issue by mfrashad** [AutodeskAILab/Clip-Forge#2]
Currently, the inference code only outputs an image rendering of the generated voxels. Is it possible to get the 3d model file as the output in .obj/.gltf format?

**Comment by aidyai** [comment]
hey bro this is not like a reply from Autodesk
i need help from you in terms of you showing me how you were able to train
i have this error
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [37], in <module>
      1 if __name__ == "__main__":
----> 2     main()

Input In [35], in main()
      1 def main():
      2     args = parsing()
----> 3     exp_name = experiment_name(args)
      5     manualSeed = args.seed
      6     helper.set_seed(manualSeed)

Input In [20], in experiment_name(args)
      1 def experiment_name(args):
      3     from datetime import datetime
----> 5     tokens = ["Autoencoder", args.dataset_name, args.input_type, args.output_type, args.encoder_type, args.decoder_type, args.emb_dims,  args.reconstruct_loss_type, args.last_feature_transform]
      7     if args.categories != None:
      8         for i in args.categories:

AttributeError: 'NoneType' object has no attribute 'dataset_name'
`

how were you able to move through this

**Comment by NelBlue** [comment]
how did you execute your code? Which files are you executing. Also, this should probably be posted in its own issue

**Comment by sanghiad** [comment]
Hi @mfrashad, sorry for the delayed response. We can generate obj format using the function  save_mesh in https://github.com/AutodeskAILab/Clip-Forge/blob/main/utils/visualization.py. I decided not to add it as it can interfere with some people running this repo as you need to compile some c++ code.

**Comment by sanghiad** [comment]
@sigmoidLabs0-1, did you install the dataset from occupancy networks?

**Comment by Utopiah** [comment]
I see that `save_mesh()` from `visualization.py` would do but I'm wondering what's the point here. I'm not sure about the resulting size of the generations of all assets but based on the number of categories that might not be larger than a model. If so then one could consider publishing the resulting 3D models directly.

**Comment by sanghiad** [comment]
@Utopiah I am confused by your question, can you please clarify?

**Comment by Utopiah** [comment]
@sanghiad I misunderstood the paper. I thought the result was finite and of reasonable size e.g 1000 objects but it seems to be truly combinatorial (even though limited by the dataset) so "saving everything" is probably prohibitive.
