### ISSUE TITLE
Why do you visualize the results with voxel grids?

### ISSUE THREAD

**Issue by bluestyle97** [AutodeskAILab/Clip-Forge#5]
Congratulations on this fancy work! But I'm wondering why you visualize the generated shape with voxel grids instead of the mesh in the paper. Since Clip-forge adopts an implicit shape decoder, I think it's convenient to extract the iso-surface.

**Comment by sanghiad** [comment]
@bluestyle97 thanks. Visually we found voxels to have more impressive results than mesh based on the rendering as described in the appendix of the paper. I believe a future work direction would involve improving the quality of the shapes generated.
